### ISSUE TITLE
GitHub Actions to deploy Hugo to GitHub Pages

### ISSUE THREAD

**Issue by PanZiwei** [PanZiwei/PanZiwei.github.io#9]
[使用 GitHub Actions 部署 Hugo 博客到 GitHub Pages](https://github.com/reuixiy/io-oi.me/issues/90)

**Comment by PanZiwei** [comment]
1. Add workflow
Github page -> Actions ->set up a workflow yourself
```
# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Building...'
        uses: actions/checkout@v2
        # .github/workflows/build.yml
        env:
        DEPLOY_REPO: PanZiwei/PanZiwei.github.io
        DEPLOY_BRANCH: master
        DEPLOY_KEY: ${{ secrets.ACITON_DEPLOY_KEY }} # The secret key name in repo
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: America/New_York

2. Generate SSH public/private key pair

```
Your identification has been saved in /Users/ziwei/.ssh/id_rsa.
Your public key has been saved in /Users/ziwei/.ssh/id_rsa.pub.
```

https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key for 3 & 4
https://docs.github.com/en/developers/overview/managing-deploy-keys#setup-2
3. Add deploy key to Github Pages repository 
copy ssh key to GitHub: `pbcopy < ~/.ssh/id_rsa.pub` (Mac version)
Github page -> Settings -> Deploy keys -> Add deploy key
Copy the ssh key, click "Allow write access"

4. Add a secret key to the source code repository
`pbcopy < ~/.ssh/id_rsa`
github source code -> Settings-> Secrets -> New repository secret
Save the file with name `ACTIONS_DEPLOY_KEY`
```
5. Generate `hugo --gc --minify --cleanDestinationDir`

#######For customer domain########
5. Add CNAME file under `/statics` folder
https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain
6. 


Reference:
### Chinese
https://owovo.xyz/post/%E4%BD%BF%E7%94%A8GithubActions+Hugo+GithubPages%E6%90%AD%E5%BB%BA%E5%8D%9A%E5%AE%A2.html
https://jiangbao.github.io/%E4%BD%BF%E7%94%A8gitubactions%E9%83%A8%E7%BD%B2hugo%E5%8D%9A%E5%AE%A2/
